### PR TITLE
Fixing issue with displying on windows xp

### PR DESCRIPTION
**Pull request by marttoygoy4**
Fixing an issue with latency and fonts on my windows xp machine

### CODE REVIEW

**Comment by hallzy** [comment]
you're still using XP?

**Comment by DGKSK8LIFE** [comment]
Yeah there's clearly a different problem here if you're still using XP.

**Comment by hallzy** [comment]
What browser are you using that still requires the HTML 4 doctype in order to function properly?

And you've probably heard it before, but I'm still going to say it. XP is like 7 years past end of life and It has not had security patches in many years.

Combining that with the fact that the Windows XP source code was leaked last year and there is no active development on XP, it isn't exactly what most people would call 'safe' to run, particularly connected to the internet.

**Comment by Holsterbau** [comment]
As others have said, you got a much more serious problem than based.cooking rendering properly. I would suggest that you either update your Windows to Windows 10, as it is the only Windows still supported, or install a Linux distribution and learn how to use it. You should under no circumstances use Windows XP that is connected directly to the Internet in 2021.

**Comment by marttoygoy4** [comment]
> Yeah there's clearly a different problem here if you're still using XP.

I got to admit it was working fine on my windows 2000/95 machine I forgot if I had KernelEx on it 

> As others have said, you got a much more serious problem than based.cooking not rendering properly. I would suggest that you either update your Windows to Windows 10, as it is the only Windows still supported, or install a Linux distribution and learn how to use it. You should under no circumstances use Windows XP that is connected directly to the Internet in 2021.

AHHAHA are you fucking insane to such a fucking pervert degree? I tried FreeBSD, will never use gnu-cucks, I been using some UNIX based os when I was CGI helper back in the days . eh whatever I am getting too drank, get laid kids....

>muh windows xp/7/95
Neck yourself you never feel the windows 95 themesong greeding you, you virgin

**Comment by hallzy** [comment]
Well that escalated quickly.

@LukeSmithxyz can we just close this stupid issue.

**Pull request closed without merging**
