### PR TITLE
add fresh lasagna recipe and picture

### PR DESCRIPTION
**Pull request by yiusa**

### CODE REVIEW

**Comment by LukeSmithxyz** [comment]
There's already a lasagna recipe.

**Comment by yiusa** [comment]
> There's already a lasagna recipe.

oh yeah was supposed to change that one, if you take a look at it i find it quite lackluster since it uses store bought pasta sauce etc.

**Comment by LukeSmithxyz** [comment]
Make the changes to his article and then link to separate directions for sauce so people can either follow those extra directions or buy their own. Looking on what you have, it looks like you sort of already have that in this article. You can feel free to mostly replace his.

Also, use proper markdown links. If you just paste the URL, it won't link properly.

**Comment by yiusa** [comment]
will do!

**Pull request closed without merging**
