### PR TITLE
Create recipe Apple crumble with speculaas

### PR DESCRIPTION
**Pull request by kryzar**
Add recipe `apple-crumble-speculaas.md`.

### CODE REVIEW

**Comment by LukeSmithxyz** [comment]
That photo is obscenely massive (1.56 MiB). Remove it or reduce its size.

**Comment by kryzar** [comment]
The new size is 270k. Tell me if you want more compression or anything else.

**Comment by LukeSmithxyz** [comment]
The image is still 4000x3000 and would still be the largest image on the site by far (including others that really should be shrunk). Note that the CSS-stipulated maximum for image height is 400px. It's fine for images to natively be larger, but not that much larger.

**Comment by kryzar** [comment]
Done. We should maybe add this constraint (height <= 400px) to the README. I can make a pull request if you want.

**Pull request closed without merging**
