### PR TITLE
Oaty pancakes

### PR DESCRIPTION
**Pull request by puremana**

### CODE REVIEW

**Comment by TomBT** [comment]
I think it'd be best to add Oaty Pancakes under the already created Pancake index like how Mexican Rice under the [Rice index](https://based.cooking/rice) and the Cheesey Omelet is under the [Omelet index](https://based.cooking/omelet).

**Comment by puremana** [comment]
I've moved it to the pancake index but it's a little bit different because it's not just an extra thing, it's a completely different recipe and instructions

**Comment by TomBT** [comment]
Ah I see

**Comment by LukeSmithxyz** [comment]
This should really be a different article.

**Comment by puremana** [comment]
Changed back to being a unique recipe...

**Pull request merged**
