### PR TITLE
added chicken tikka masala

### PR DESCRIPTION
**Pull request by aaronbjohnson**

### CODE REVIEW

**Review by ThamognyaKodi — COMMENTED** [review]
Great recipe. Could you convert min to an hour or vice versa for all of the units, I think a standardized time unit is better.

**Comment by hmccarty** [comment]
> Great recipe. Could you convert min to an hour or vice versa for all of the units, I think a standardized time unit is better.

Varying denominations of time is the standard, can't think of a good reason to write 240 minutes instead of 4 hours. 

Good recipe though, should merge PR.

**Comment by aaronbjohnson** [comment]
> > Great recipe. Could you convert min to an hour or vice versa for all of the units, I think a standardized time unit is better.
> 
> Varying denominations of time is the standard, can't think of a good reason to write 240 minutes instead of 4 hours.
> 
> Good recipe though, should merge PR.

That's what I thought as well. I feel like most people would prefer 30 minutes to .5 hours etc.

**Comment by aaronbjohnson** [comment]
> > Great recipe. Could you convert min to an hour or vice versa for all of the units, I think a standardized time unit is better.
> 
> Varying denominations of time is the standard, can't think of a good reason to write 240 minutes instead of 4 hours.
> 
> Good recipe though, should merge PR.

Actually I just realized that it shouldn't give a total cooking time of 4.25 hours...that is a bit weird. It should be just 4 hours cooking. I'll make the change.

**Pull request closed without merging**
