### PR TITLE
Add hearty-breakfast-oatmeal

### PR DESCRIPTION
**Pull request by J-F-Far**

### CODE REVIEW

**Comment by marttoygoy4** [comment]
image
Make sure you attach your own pictures

**Comment by J-F-Far** [comment]
I am a bit shocked and confused by this haha.... I took the submitted photos with my phone this morning. How can I sufficiently prove to you that those photos are my own?

**Comment by hallzy** [comment]
I've never used Yandex, but isn't that the 'original image'? I don't think that image was found on the internet by Yandex, I think it is just showing you what image you are searching for

**Comment by J-F-Far** [comment]
@hallzy I've never used Yandex before either. I am perhaps misinterpreting the original response to my PR... I interpreted 'Make sure you attach your own pictures' to mean 'Change the submitted pictures as they are not yours'... But I took them with my phone this morning; they are indeed mine.

@marttoygoy4 Could you clarify if there is a problem with my submission? If you believe that the submitted pictures are not my own, how can I prove to you that they are indeed pictures I took with my phone this morning?

**Comment by Holsterbau** [comment]
@hallzy you are right, it is not showing that a duplicate image exists. It just shows similar-looking images, they don't have to be identical. Yandex's reverse image search is quite sophisticated and is miles ahead of Google's reverse image search, since they spend more resources into actually making their reverse image search work than breaking their own engine to stop it from identifying black people as gorillas. That is why the Yandex's engine claims there's "sites containing this image", but @marttoygoy4 never actually checked if they're *identical* images. 

Spoiler: they are not.

Here are the links from his screenshot, and you can clearly see that, while the images are similar, they are obviously not the same.
http://www.vseblyuda.ru/item/377/konfety-iz-ovsyanki-recept-foto/
https://luera.ru/vypechka/pechenye/postnoe-solenoe-zlakovoe-pechenye

@marttoygoy4 quality of your contributions on this project leaves a lot to be desired.

**Comment by hallzy** [comment]
@Holsterbau dude, chill.

> it is not showing that a duplicate image exists. It just shows similar-looking images

If you knew this then why post the screenshot and waste our time?

> but @marttoygoy4 never actually checked if they're identical images.

Why on earth would he look? If he did steal the image from the internet then he knows he took it so there is no point, if he took the picture himself why would he look, because he knows he took it? This logic makes no sense.

> @marttoygoy4 quality of your contributions on this project leaves a lot to be desired.

What is the purpose of attacking people? At least he is contributing and actually adding images to his recipes unlike someone...

**Comment by Holsterbau** [comment]
I think you are confused here. @J-F-Far is the pull requester, the person you are evidently talking about. I am not talking about him, or directing any of my statements at him, his pull request is perfectly OK. I am talking about the other person in this pull request, @marttoygoy4, the person who derails this pull request with a silly Yandex search.

**Pull request merged**
