### PR TITLE
added pork carnitas & slow-cooked tag

### PR DESCRIPTION
**Pull request by smantha69**
there are no tags for slow-cooked but there's precedent for stylizing it as `slow-cooked` [here](https://based.cooking/chicken-tacos) (where i've also added that tag)

### CODE REVIEW

**Comment by endlesslake** [comment]
You should replace the `chicken` tag with `pork`

**Comment by smantha69** [comment]
> 
> 
> You should replace the `chicken` tag with `pork`

what?

**Comment by hallzy** [comment]
I think @endlesslake thought you added the chicken tag to your pork recipe. But the chicken tag is on a chicken taco recipe

**Review by zyansheep — APPROVED** [review]
Looks good,
you have an extra space before direction # 6  but that's probably fine

**Comment by endlesslake** [comment]
> I think @endlesslake thought you added the chicken tag to your pork recipe. But the chicken tag is on a chicken taco recipe

That was it. My mistake

**Pull request merged**
