### PR TITLE
Added Minimalist Bread recipe with pictures

### PR DESCRIPTION
**Pull request by Zgrab123**

### CODE REVIEW

**Review by marttoygoy4 — COMMENTED** [review]
Are these taken from the internet or yours ? Luke has asked for your own pictures, I like the idea

**Comment by Zgrab123** [comment]
> Are these taken from the internet or yours ? Luke has asked for your own pictures, I like the idea

Hi, Thank you, those are my own pictures I took during the creation of the recipe! Hopefully they convey the idea well, please excuse any errors

**Comment by hallzy** [comment]
Could you rename the markdown file to have a `.md` extensions on it, so everything is consistent

**Comment by Zgrab123** [comment]
> Could you rename the markdown file to have a `.md` extensions on it, so everything is consistent

Yes, thank you, sorry for inconvenience

**Pull request closed without merging**
