### PR TITLE
Create Carbonara.md

### PR DESCRIPTION
**Pull request by ppiont**
added carbonara

### CODE REVIEW

**Comment by LukeSmithxyz** [comment]
Add it to the index.

**Comment by ppiont** [comment]
fixed

**Comment by LukeSmithxyz** [comment]
That pic directly linked from the page is 7 megs.

**Comment by ppiont** [comment]
259.4 kb now

**Comment by ppiont** [comment]
What is the reason for not merging this?

**Comment by LukeSmithxyz** [comment]
I want to be sure about some things before I commit another image to the repo.

**Comment by ppiont** [comment]
> I want to be sure about some things before I commit another image to the repo.

Alright. I made some small adjustments to the text and renamed the .md to conform with all lowercase.

**Pull request merged**
