### PR TITLE
More simple egg recipes for eggs.md

### PR DESCRIPTION
**Pull request by dther**
I like eggs.

### CODE REVIEW

**Comment by siggines** [comment]
There is already an eggs recipe page, https://based.cooking/eggs , you may want to incoroporate your stuff into that file instead?

**Comment by siggines** [comment]
The 'tips' sections seem a bit verbose to me, making the eggs file a long document. Also most of that advice such as how to whisk properly could be stated in the directions. Just for the sake of being concise maybe remove or shorten those sections?

**Comment by dther** [comment]
> The 'tips' sections seem a bit verbose to me, making the eggs file a long document. Also most of that advice such as how to whisk properly could be stated in the directions. Just for the sake of being concise maybe remove or shorten those sections?

Fair point. Is this better?

**Review by siggines — APPROVED** [review]
> Fair point. Is this better?

Lovely, thanks for taking the time.

**Pull request closed without merging**
