### PR TITLE
Add oats

### PR DESCRIPTION
**Pull request by m-chrzan**
Adds oats.

### CODE REVIEW

**Comment by LukeSmithxyz** [comment]
Idk, oats are p cringe/non-based. I'll think about it.

**Comment by LukeSmithxyz** [comment]
The only reason I included a pasta page is because it is an ingredient in other dishes that a NEET somehow might not know how to boil. I would rather link the page from other pages rather than routinely recite the same directions.

**Comment by twiclo** [comment]
Oats are great for bulking which is when you should be eating carbs/pasta

**Comment by LukeSmithxyz** [comment]
I'll give in, but I stand by that oat consumption is always cringe.

**Pull request merged**
