### PR TITLE
add based protein shake

### PR DESCRIPTION
**Pull request by binex-dsk**
v

### CODE REVIEW

**Review by DGKSK8LIFE — CHANGES_REQUESTED** [review]
More descriptive title plz

**Comment by binex-dsk** [comment]
ok fixed

**Review by DGKSK8LIFE — APPROVED** [review]
Whatever lol

**Comment by alzheimerspenguin** [comment]
As funny as this conversation is, protein powder (of any type) and peanut butter (100% polyunsaturated fat) are neither hyperborean nor lindy, they are turbozog garbage that should not be eaten in any quantity.

An example "lindy" "protein shake" with traditional ingredients for the purpose of skipping a solid meal & meeting intake requirements for mass would be something like:

six eggs
1L whole milk
1 banana
400g (real) ice cream

https://raypeat.com/articles/articles/unsuitablefats.shtml
https://raypeat.com/articles/articles/unsaturated-oils.shtml

**Comment by binex-dsk** [comment]
>400g ice cream

Haha fat

>100% polyunsaturated fat

mostly monounsaturated which raises T levels

and if you're gonna do that much, might as well go for the 36 eggs a day diet, because if you only have this you're gonna get the soylent jaw

**Comment by alzheimerspenguin** [comment]
I can only try to give you information, if you've convinced yourself you know everything then you cannot learn.

"Based Cooking" /= Protein Powder

**Comment by binex-dsk** [comment]
your "replacement" is not even close to "based cooking". That is basically a hyper-sugary version of Soylent--literally just calories and barely any minerals, plus seems to be a full LIQUID meal REPLACEMENT, so have fun with jaw destruction.  meme-tier and hyper-sugary, and as explicitly stated on the README are not allowed. Protein powder and peanut butter are not "turbozog garbage", they are T raising machines.

**Review by DGKSK8LIFE — APPROVED** [review]

**Comment by binex-dsk** [comment]
@LukeSmithxyz why?

**Pull request closed without merging**
