### PR TITLE
Added Apple Pie, Chocolate Chip Cookies, Ragu Napoletano, Limoncello, Italian Mulled Wine, Mapo Tofu, Ravioli recipes

### PR DESCRIPTION
**Pull request by mfed3**

### CODE REVIEW

**Comment by Knarkzel** [comment]
Very good. You don't need to add salt to ingredients list.

**Comment by mfed3** [comment]
> Very good. You don't need to add salt to ingredients list.

Thanks, I'm tracking the no salt and pepper request, but it's different for a baking ingredient where it can change the structure and consistency. I say to leave it in baking recipes but take it out of any "salt and pepper to taste" types.

**Comment by mfed3** [comment]
@Knarkzel, is this going to get merged? Are there issues or do you want me to open a new pull request? I'm seeing hundreds of pull requests merged that were created after mine and I'm just wondering what needs to get done.

**Comment by mfed3** [comment]
Hey @LukeSmithxyz just trying to get a resolution on the pull request. Is this something that needs resolution at your level? Or is it just in a queue? I'd love to keep working on putting my recipes into the site but I'm hesitant to put any time in if they are going to just sit with no comments attached. Thanks!

**Comment by mfed3** [comment]
Not being approved for 22 days, workflow seems flawed

**Pull request closed without merging**
