### PR TITLE
make light theme look nicer

### PR DESCRIPTION
**Pull request by bozo22**
The original light theme looks pretty ugly and generic, also it doesn't fit the dark theme's color scheme so i just tweaked a few colors in the css to make it look nicer.

Untitled

### CODE REVIEW

**Comment by marttoygoy4** [comment]
I signed for this!

**Comment by marttoygoy4** [comment]
We need Soyfied.JS lol this project really gives me vibes of OH SHIT THIS IS THE FUTURE
honestly I would like a JS slide bar that could resize the text 
image
image


when they make javascript bloated its bad I dont think javascript should be used that way, they are many parts I HATE about javascript I think the main idea of javascript where it let you add and costomize your thing is "where its at" not 1mb of fucking javascript lol


also check out this javascript 
image
This is how I think javascript should be used no otherway

**Comment by LukeSmithxyz** [comment]
Idk. I'll think about. Honestly nothing looks good to me in light theme, but I feel like neither one works too well so far.

**Comment by oussamabouchareb** [comment]
> Idk. I'll think about. Honestly nothing looks good to me in light theme, but I feel like neither one works too well so far.

I don't think anyone would complain if you made dark theme the default theme and removed white theme completely

**Comment by taco-c** [comment]
I don't think those changes look better; I like the current look. Nothing wrong with generic.

> I don't think anyone would complain if you made dark theme the default theme and removed white theme completely

I would.

**Comment by marttoygoy4** [comment]
> The original light theme looks pretty ugly and generic, also it doesn't fit the dark theme's color scheme so i just tweaked a few colors in the css to make it look nicer.
> 
> Untitled
Reminds me that old russian website I used to love! 
image

**Comment by marttoygoy4** [comment]
image
I know the argument against javascript I hate HTML5 too, but I made a javascript/userscript plugin to add this pull :) 
no bs, just niceness :)

```
// ==UserScript==
// @name        New script - based.cooking
// @namespace   Violentmonkey Scripts
// @match       https://based.cooking/
// @grant       none
// @version     1.0
// @author      -
// @description 3/20/2021, 7:09:37 PM
// @run-at   document-start
// ==/UserScript==


function GM_addStyle (cssStr) {
    var D               = document;
    var newNode         = D.createElement ('style');
    newNode.textContent = cssStr;

    var targ    = D.getElementsByTagName ('head')[0] || D.body || D.documentElement;
    targ.appendChild (newNode);
}

GM_addStyle ( `
	body {
		background: #F2F4F3 ;
		color: #1F1E1F ;
	}
	a {
		color: tomato ;
	}
	a:visited {
		color: gray ;
`);```

**Pull request closed without merging**
