### PR TITLE
Proper Dark Mode Support

### PR DESCRIPTION
**Pull request by Oshgnacknak**
These four CSS lines are enough for some nice Dark Mode action.
image
- Osh

### CODE REVIEW

**Comment by LukeSmithxyz** [comment]
Okay. I'm going to leave this open for a bit to think about it or see if others have opinions.

I am 100% pro-dark (and think it should always be default), but I don't know if it's a turn off for some people.

**Comment by DominikRusso** [comment]
Using [prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) might be an alternative.

**Comment by LukeSmithxyz** [comment]
How commonly is that actually set? Is that typical in browsers or something without me knowing?

**Comment by LukeSmithxyz** [comment]
Oh, actually, it looks like I already have dark mode as default without even remembering. I think I'll go ahead and add these settings in a `prefers-color-scheme` statement. I am still open to the idea of dark as default though.

Also, I'm still open to whatever kind of tweaks to either the dark or light color schemes.

**Comment by DominikRusso** [comment]
In normie operating systems (win and mac) the browser gets the preference from the OS. In linux you can enable it by passing `--force-dark-mode` or enabling it in the flags (`chrome://flags/#enable-force-dark`).

**Comment by 0neGal** [comment]
> How commonly is that actually set? Is that typical in browsers or something without me knowing?

More than you'd think, iOS 13 and up sets it, Windows and macOS has been setting it since forever, and your QT and GTK theme also sets it automatically in most browsers.

The preferable way to handle this would be with:
```css
@media (prefers-color-scheme:dark) {
    body {
        color: white;
        background-color: black;
    }
}
```

Obviously adjusting the colors to your liking.

You can also furthermore add:
```css
@media (prefers-color-scheme:light) {
    body {
        color: black;
        background-color: white;
    }
}
```
To fix issues like this
2021-03-10_Wed-Mar_09-29-34

In my case QuteBrowser can only set the default browser background and not foreground, so some sites look like this.

**Pull request closed without merging**
